name: precise_compass_example
description: Demonstrates the precise_compass plugin (heading, accuracy, fusion).
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1

  precise_compass:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: true
